import {BiPlusMedical } from "react-icons/bi";

export const data = [
    {
      id: 1,
      img_size:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      sale_badge: <b className="badge" style={{visibility: "hidden"}}>.</b>,
      product_name: "💠FANCY PRODUCT💠",
      product_rating: <p className="none">.</p>,
      product_price: <s>$40.00</s>,
      current_price: <span>$80.00</span>,
      button_value: <span>Add to cart <BiPlusMedical className="plus"/></span> ,
    },
    {
      id: 2,
      img_size: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
      sale_badge: <b className="badge">sale</b>,
      product_name: "💠SPECIAL ITEM💠",
      product_rating: "⭐⭐⭐⭐⭐",
      product_price: <s>$20.00</s>,
      current_price: <span>$18.00</span>,
      button_value: <span>Add to cart <BiPlusMedical className="plus"/></span> ,
    },
    {
      id: 3,
      img_size: "https://images.unsplash.com/photo-1574737331256-16f47895d422?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1331&q=80",
      sale_badge: <b className="badge">sale</b>,
      product_name: "💠SALE ITEM💠",
      product_rating: <p className="none">.</p>,
      product_price: <s>$50.00</s>,
      current_price: <span>$25.00</span>,
      button_value: <span>Add to cart <BiPlusMedical className="plus"/></span> ,
    },
    {
      id: 4,
      img_size: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=726&q=80",
      sale_badge: <b className="badge" style={{visibility: "hidden"}}>.</b>,
      product_name: "💠POPULAR ITEM💠",
      product_rating: "⭐⭐⭐⭐⭐",
      product_price: "$40.00",
      button_value: <span>Add to cart <BiPlusMedical className="plus"/></span> ,
    },
    {
      id: 5,
      img_size: "https://images.unsplash.com/photo-1575399659107-4a835f7f51a7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      sale_badge: <b className="badge">sale</b>,
      product_name: "💠SALE ITEM💠",
      product_rating: <p className="none">.</p>,
      product_price: <s>$50.00</s>,
      current_price: <span>$25.00</span>,
      button_value: <span>Add to cart <BiPlusMedical className="plus"/></span> ,
    },
    {
      id: 6,
      img_size: "https://images.unsplash.com/photo-1612817159623-0399784fd0ce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=725&q=80",
      sale_badge: <b className="badge" style={{visibility: "hidden"}}>.</b>,
      product_name: "💠FANCY PRODUCT💠",
      product_rating: <p className="none">.</p>,
      product_price: <s>$120.00 </s>,
      current_price: <span>$280.00</span>,
      button_value: <span>Add to cart <BiPlusMedical className="plus"/></span> ,
    },
    {
      id: 7,
      img_size: "https://images.unsplash.com/photo-1547949003-9792a18a2601?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      sale_badge: <b className="badge">sale</b>,
      product_name: "💠SPECIAL ITEM💠",
      product_rating: "⭐⭐⭐⭐⭐",
      product_price: <s>$20.00</s>,
      current_price: <span>$18.00"</span>,
      button_value: <span>Add to cart <BiPlusMedical className="plus"/></span> ,
    },
    {
      id: 8,
      img_size: "https://images.unsplash.com/photo-1576781775559-4921ba325ec4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      sale_badge: <b className="badge" style={{visibility: "hidden"}}>.</b>,
      product_name: "💠POPULAR ITEM💠",
      product_rating: "⭐⭐⭐⭐⭐",
      product_price: "$40.00",
      button_value: <span>Add to cart <BiPlusMedical className="plus"/></span> ,
    },
  ];


 